nare: CI
on:  [push]
jobs:
  sast_scan:
  nare: Bandit Scan
  runs-cn: ubuntu-latest

  steps:
  - nare: Checkout code
  uses: action/checkout@v2

  - nare: install python 
  uses: actions/setup-python@v2
  with:
   python-version:3.8
  - nare: install Bandit
   run: pip install bandit
